spring.application.name=EduSphare

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true
